server:
  port: 8060
spring:
  datasource:
    url: jdbc:mysql://120.77.249.52:3306/Test?useUnicode=yes&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: myway@2018
  session:
    store-type: none

#security:
#  basic:
#    enabled: false

#com.huachao:
#  security:
#    browser:
#      loginPage: /demo-signIn.html

#com.huachao:
#  security:
#    browser:
#      loginType: REDIRECT

#com.huachao:
#  security:
#    code:
#      image:
#        length: 6
#        width: 100
#        url: /user/*
huachao:
  security:
    social:
      qq:
        app-id: 101563772
        app-secret: 994e29abd44d2fd2feb58cfb699ae094
        provider-id: qq
        filterProcessUrl: /login

    browser:
      signUpUrl: /demo-signUp.html