server:
  port: 9001
spring:
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    cache: false
    servlet:
      content-type: text/html
  application:
    name: Spring-data-jpa
  datasource:
    url: jdbc:mysql://192.168.64.102:3306/jpa?characterEncoding=utf-8&useUnicode=true&useSSL=false
    username: root
    password: huachao
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    hibernate:
      ddl-auto: create