server:
  port: 9001
spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.64.102:3333,192.168.64.102:4444,192.168.64.102:5555
management:
  endpoints:
    web:
      exposure:
        include: "*"