server:
  port: 9005
spring:
  application:
    name: sentinel-client
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
    nacos:
      discovery:
        server-addr: 192.168.64.102:80
  devtools:
    restart:
      enabled: true
  freemarker:
    cache: false
management:
  endpoints:
    web:
      exposure:
        include: "*"